name: Build AutoGrader EXE
on: [push, workflow_dispatch] # 每次上傳或手動啟動時執行

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install pyinstaller pymupdf customtkinter pandas openpyxl python-docx google-generativeai
      - name: Build EXE
        run: |
          pyinstaller --noconsole --onefile --collect-all fitz AutoGrader_cloud.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AutoGrader-Finished-EXE
          path: dist/AutoGrader_cloud.exe
